name: Snyk Analysis
env:
  DOTNET_VERSION: '8.x'
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: snyk/actions/setup@master

      - name: Configurar versión de .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Instalar snyk-to-html
        run: npm install -g snyk-to-html

      - name: Ejecutar Snyk Code Test y generar HTML
        run: snyk code test --json | snyk-to-html -o code-report.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Subir reporte HTML como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: snyk-code-report
          path: code-report.html
